# Generated by Django 2.0.1 on 2018-04-26 15:46

import account.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_type', models.CharField(default='Regular User', max_length=32)),
                ('problem_permission', models.CharField(default='None', max_length=32)),
                ('reset_password_token', models.CharField(max_length=32, null=True)),
                ('reset_password_token_expire_time', models.DateTimeField(null=True)),
                ('auth_token', models.CharField(max_length=32, null=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('tfa_token', models.CharField(max_length=32, null=True)),
                ('session_keys', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('open_api', models.BooleanField(default=False)),
                ('open_api_appkey', models.CharField(max_length=32, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acm_problems_status', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('oi_problems_status', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('small_problems_status', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('real_name', models.CharField(blank=True, max_length=32, null=True)),
                ('avatar', models.CharField(default='/public/avatar/default.png', max_length=256)),
                ('blog', models.URLField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=256, null=True)),
                ('github', models.CharField(blank=True, max_length=64, null=True)),
                ('school', models.CharField(blank=True, max_length=64, null=True)),
                ('major', models.CharField(blank=True, max_length=64, null=True)),
                ('accepted_number', models.IntegerField(default=0)),
                ('total_score', models.BigIntegerField(default=0)),
                ('submission_number', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
