# Generated by Django 2.0.1 on 2018-03-15 09:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171125_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='small_problems_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
