# Generated by Django 2.0.1 on 2018-03-14 07:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contest_allowed_ip_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0010_problem_spj_compile_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, max_length=24)),
                ('type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('description', utils.models.RichTextField()),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('visible', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('submission_number', models.BigIntegerField(default=0)),
                ('accepted_number', models.BigIntegerField(default=0)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'small_problem',
            },
        ),
        migrations.CreateModel(
            name='SmallTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'small_tag',
            },
        ),
        migrations.AddField(
            model_name='smallproblem',
            name='tags',
            field=models.ManyToManyField(to='problem.SmallTag'),
        ),
    ]
