# Generated by Django 2.0.1 on 2018-03-15 09:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20180314_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallproblem',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
