# Generated by Django 2.0.1 on 2018-03-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contest_allowed_ip_ranges'),
        ('problem', '0012_smallproblem_statistic_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallproblem',
            options={'ordering': ('create_time',)},
        ),
        migrations.AlterUniqueTogether(
            name='smallproblem',
            unique_together={('_id', 'contest')},
        ),
    ]
